/**
 * English translations
 */

export default {
  // Common
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    apply: 'Apply',
    update: 'Update',
    back: 'Back',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading...',
    actions: 'Actions',
    options: 'Options',
    name: 'Name',
    type: 'Type',
    auto: '(auto)',
  },

  // Header
  header: {
    pendingChanges: 'Pending Changes',
    noChanges: 'No Changes',
    validationErrors: 'Validation Errors',
    publishVersion: 'Publish Version',
    connected: 'Connected',
    disconnected: 'Disconnected',
  },

  // Navigation
  nav: {
    home: 'Home',
    settings: 'Settings',
    objects: 'Objects',
    enums: 'Enums',
    history: 'History',
    newEnum: 'New Enum',
  },

  // Home page
  home: {
    title: 'Schemas',
    newSchema: 'New Schema',
    createFirst: 'Create First Schema',
    noSchemas: 'No schemas found',
    properties: '{{count}} properties',
    values: '{{count}} values',
    deleteConfirm: 'Delete schema "{{name}}"?',
    pendingChanges: '{{count}} Changes',
    noChanges: 'No Changes',
    fields: 'Fields',
  },

  // Schema editor
  schema: {
    newSchema: 'New Schema',
    editSchema: 'Edit Schema',
    createSchema: 'Create Schema',
    saveChanges: 'Save Changes',
    schemaName: 'Schema Name',
    displayName: 'Display Name',
    kind: 'Kind',
    kindObject: 'Object',
    kindEnum: 'Enum',
    singular: 'Singular',
    plural: 'Plural',
    group: 'Group',
    tableName: 'Custom Table Name',
    titleField: 'Title Field',
    primaryKey: 'Auto ID',
    noPrimaryKey: 'None',
    timestamps: 'Timestamps',
    softDelete: 'Soft Delete',
    translations: 'Translations',
    authenticatable: 'Authenticatable',
    loginIdField: 'Login ID Field',
    passwordField: 'Password Field',
    guardName: 'Guard Name',
    authConfig: 'Auth Config',
    schemaCreated: 'Schema "{{name}}" created',
    schemaSaved: 'Schema "{{name}}" saved',
    // Dual-mode editor
    visualMode: 'Visual',
    codeMode: 'YAML',
    yamlEditor: 'YAML Editor',
    yamlParseError: 'YAML syntax error',
    // Virtual fields
    fieldId: 'ID',
    fieldCreatedAt: 'Created At',
    fieldUpdatedAt: 'Updated At',
    fieldDeletedAt: 'Deleted At',
    // Type display
    typeAssociation: 'Association',
  },

  // Properties
  property: {
    title: 'Properties',
    addProperty: 'Add Property',
    editProperty: 'Edit Property',
    propertyName: 'Property Name',
    noProperties: 'No properties defined. Click "Add Property" to start.',
    deleteConfirm: 'Delete this property?',
    nullable: 'Nullable',
    unique: 'Unique',
    primaryKey: 'Primary Key',
    autoIncrement: 'Auto Increment',
    unsigned: 'Unsigned',
    positiveOnly: 'Unsigned (positive only)',
    defaultValue: 'Default Value',
    defaultPlaceholder: 'Leave empty for no default',
    description: 'Description',
    descriptionPlaceholder: 'Field description/comment',
    maxLength: 'Max Length',
    precision: 'Precision (Total Digits)',
    scale: 'Scale (Decimal Places)',
    enumReference: 'Enum Reference or Values',
    inlineEnumValues: 'Inline Enum Values',
    inlineEnumHint: 'Type values and press Enter. E.g.: active, pending, closed',
    enumSchemaRef: 'Enum Schema Reference',
    selectEnumSchema: 'Select enum schema',
    selectOptions: 'Options (for Select)',
    sourceSchema: 'Source Schema (for Lookup)',
    references: 'References',
    settings: 'Settings',
    index: 'Index',
  },

  // Associations
  association: {
    relationType: 'Relation Type',
    targetSchema: 'Target Schema',
    targetSchemas: 'Target Schemas (Polymorphic)',
    morphName: 'Morph Name',
    advancedOptions: 'Advanced Options',
    inversedBy: 'Inversed By',
    mappedBy: 'Mapped By',
    onDelete: 'On Delete',
    onUpdate: 'On Update',
    joinTable: 'Custom Join Table Name',
    owning: 'Owning Side (has foreign key)',
    standardRelations: 'Standard Relations',
    polymorphicRelations: 'Polymorphic Relations',
  },

  // Indexes
  index: {
    title: 'Indexes',
    addIndex: 'Add Index',
    editIndex: 'Edit Index',
    columns: 'Columns',
    indexName: 'Index Name (optional)',
    indexType: 'Index Type',
    uniqueIndex: 'Unique Index',
    noIndexes: 'No indexes defined. Click "Add Index" to optimize queries.',
    deleteConfirm: 'Delete this index?',
    selectColumns: 'Select columns for this index',
    autoGenerated: 'Auto-generated if empty',
    duplicateName: 'Index name "{{name}}" already exists',
  },

  // Unique Constraints
  unique: {
    title: 'Unique Constraints',
    addConstraint: 'Add Constraint',
    editConstraint: 'Edit Constraint',
    noConstraints: 'No unique constraints defined. Click "Add Constraint" to enforce uniqueness across columns.',
    deleteConfirm: 'Delete this constraint?',
    selectColumns: 'Select columns for this unique constraint',
  },

  // Enum
  enum: {
    title: 'Enum Values',
    addValue: 'Add Value',
    noValues: 'No enum values defined. Click "Add Value" to start.',
    value: 'Value',
    label: 'Label',
    extra: 'Extra',
    deleteConfirm: 'Delete this value?',
    displayLabel: 'Display Label (for forms)',
    extraProperties: 'Extra Properties',
    noExtraProperties: 'No extra properties. Add custom fields like bgColor, textColor, icon, order, etc.',
  },

  // Settings
  settings: {
    title: 'Settings',
    database: 'Database',
    databaseType: 'Database Type',
    databaseHint: 'This affects available index types and SQL generation.',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    showPreview: 'Show Preview Panel',
    language: 'Language',
    serverConfig: 'Server Configuration',
    schemasDir: 'Schemas Directory',
    serverPort: 'Server Port',
    host: 'Host',
    plugins: 'Plugins',
    noPlugins: 'No plugins installed. Install with: npm install @famgia/omnify-japan',
    pluginsHint: 'Enable/disable plugins to add custom types. Changes require server restart.',
    pluginEnabled: '{{name}} plugin enabled',
    pluginDisabled: '{{name}} plugin disabled',
    pluginToggleError: 'Failed to toggle plugin',
    serverRestarting: 'Server Restarting...',
    pleaseWait: 'Please wait while the server restarts',
    serverRestartFailed: 'Server restart failed. Please restart manually.',
    pluginConfiguration: 'Configuration',
    savePluginConfig: 'Save Configuration',
    pluginConfigSaveError: 'Failed to save plugin configuration',
  },

  // Preview
  preview: {
    title: 'Code Preview',
    laravel: 'Laravel',
    typescript: 'TypeScript',
    sql: 'SQL',
    laravelMigration: 'Laravel Migration',
    rawSql: 'Raw SQL',
    noPreview: 'No preview available',
  },

  // History
  history: {
    title: 'Version History',
    version: 'Version',
    migration: 'Migration',
    description: 'Description',
    changes: 'Changes',
    timestamp: 'Timestamp',
    noVersions: 'No versions found. Generate a migration to create the first version.',
    versionDetail: 'Version Detail',
    driver: 'Driver',
    schemaSnapshot: 'Schema Snapshot',
    noChangesRecorded: 'No changes recorded',
    diff: 'Diff',
    noChangesBetween: 'No changes between versions',
    changesDetected: '{{count}} change(s) detected',
  },

  // Changes
  changes: {
    analyzing: 'Analyzing schema changes...',
    errorLoading: 'Error Loading Changes',
    unableToLoad: 'Unable to load changes',
    noChanges: 'No Changes Detected',
    upToDate: 'Your schemas are up to date with version {{version}}.',
    initial: 'initial',
    totalChanges: 'Total Changes',
    added: 'Added',
    modified: 'Modified',
    removed: 'Removed',
    comparingWith: 'Comparing with version {{version}}',
    initialVersion: 'Initial version - all schemas are new',
    schemasInProject: '{{count}} schemas in current project',
    pendingPreview: 'Pending Changes Preview',
    close: 'Close',
    generateMigration: 'Generate Migration',
    discardChanges: 'Discard Changes',
    discardConfirm: 'Discard all changes?',
    discardConfirmDesc: 'This will restore all schemas to the latest version. This action cannot be undone.',
    discardYes: 'Discard',
    cancel: 'Cancel',
    discardSuccess: 'Restored {{restored}} schemas, deleted {{deleted}} new schemas',
  },

  // Common errors
  error: {
    title: 'Error',
  },

  // Validation
  validation: {
    required: '{{field}} is required',
    invalidName: 'Invalid property name',
    selectAtLeastOne: 'Select at least one column',
  },

  // Unsaved changes
  unsaved: {
    title: 'Unsaved Changes',
    message: 'You have unsaved changes. Are you sure you want to leave this page?',
    leave: 'Leave',
    stay: 'Stay',
  },
};
