/**
 * Japanese translations
 */

export default {
  // Common
  common: {
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    add: '追加',
    apply: '適用',
    update: '更新',
    back: '戻る',
    yes: 'はい',
    no: 'いいえ',
    loading: '読み込み中...',
    actions: '操作',
    options: 'オプション',
    name: '名前',
    type: '型',
    auto: '(自動)',
  },

  // Header
  header: {
    pendingChanges: '保留中の変更',
    noChanges: '変更なし',
    validationErrors: '検証エラー',
    publishVersion: 'バージョン公開',
    connected: '接続済み',
    disconnected: '切断',
  },

  // Navigation
  nav: {
    home: 'ホーム',
    settings: '設定',
    objects: 'オブジェクト',
    enums: '列挙型',
    history: '履歴',
    newEnum: '新規列挙型',
  },

  // Home page
  home: {
    title: 'スキーマ',
    newSchema: '新規スキーマ',
    createFirst: '最初のスキーマを作成',
    noSchemas: 'スキーマが見つかりません',
    properties: '{{count}} プロパティ',
    values: '{{count}} 値',
    deleteConfirm: 'スキーマ「{{name}}」を削除しますか？',
    pendingChanges: '{{count}} 変更',
    noChanges: '変更なし',
    fields: 'フィールド',
  },

  // Schema editor
  schema: {
    newSchema: '新規スキーマ',
    editSchema: 'スキーマ編集',
    createSchema: 'スキーマ作成',
    saveChanges: '変更を保存',
    schemaName: 'スキーマ名',
    displayName: '表示名',
    kind: '種類',
    kindObject: 'オブジェクト',
    kindEnum: '列挙型',
    singular: '単数形',
    plural: '複数形',
    group: 'グループ',
    tableName: 'カスタムテーブル名',
    titleField: 'タイトルフィールド',
    primaryKey: 'Auto ID',
    noPrimaryKey: 'なし',
    timestamps: 'タイムスタンプ',
    softDelete: '論理削除',
    translations: '多言語対応',
    authenticatable: '認証可能',
    loginIdField: 'ログインIDフィールド',
    passwordField: 'パスワードフィールド',
    guardName: 'ガード名',
    authConfig: '認証設定',
    schemaCreated: 'スキーマ「{{name}}」を作成しました',
    schemaSaved: 'スキーマ「{{name}}」を保存しました',
    // Dual-mode editor
    visualMode: 'ビジュアル',
    codeMode: 'YAML',
    yamlEditor: 'YAMLエディタ',
    yamlParseError: 'YAML構文エラー',
    // Virtual fields
    fieldId: 'ID',
    fieldCreatedAt: '作成日時',
    fieldUpdatedAt: '更新日時',
    fieldDeletedAt: '削除日時',
    // Type display
    typeAssociation: 'リレーション',
  },

  // Properties
  property: {
    title: 'プロパティ',
    addProperty: 'プロパティ追加',
    editProperty: 'プロパティ編集',
    propertyName: 'プロパティ名',
    noProperties: 'プロパティが定義されていません。「プロパティ追加」をクリックして開始してください。',
    deleteConfirm: 'このプロパティを削除しますか？',
    nullable: 'NULL許可',
    unique: 'ユニーク',
    primaryKey: '主キー',
    autoIncrement: '自動増分',
    unsigned: '符号なし',
    positiveOnly: '符号なし（正の値のみ）',
    defaultValue: 'デフォルト値',
    defaultPlaceholder: '空のままでデフォルト値なし',
    description: '説明',
    descriptionPlaceholder: 'フィールドの説明・コメント',
    maxLength: '最大長',
    precision: '精度（総桁数）',
    scale: 'スケール（小数点以下桁数）',
    enumReference: '列挙型参照または値',
    inlineEnumValues: 'インライン列挙値',
    inlineEnumHint: '値を入力してEnterを押してください。例：active, pending, closed',
    enumSchemaRef: '列挙型スキーマ参照',
    selectEnumSchema: '列挙型スキーマを選択',
    selectOptions: 'オプション（Select用）',
    sourceSchema: 'ソーススキーマ（Lookup用）',
    references: '参照',
    settings: '設定',
    index: 'インデックス',
  },

  // Associations
  association: {
    relationType: 'リレーション型',
    targetSchema: 'ターゲットスキーマ',
    targetSchemas: 'ターゲットスキーマ（ポリモーフィック）',
    morphName: 'モーフ名',
    advancedOptions: '詳細オプション',
    inversedBy: '逆参照',
    mappedBy: 'マップ元',
    onDelete: '削除時',
    onUpdate: '更新時',
    joinTable: 'カスタム中間テーブル名',
    owning: '所有側（外部キーを持つ）',
    standardRelations: '標準リレーション',
    polymorphicRelations: 'ポリモーフィックリレーション',
  },

  // Indexes
  index: {
    title: 'インデックス',
    addIndex: 'インデックス追加',
    editIndex: 'インデックス編集',
    columns: 'カラム',
    indexName: 'インデックス名（任意）',
    indexType: 'インデックス型',
    uniqueIndex: 'ユニークインデックス',
    noIndexes: 'インデックスが定義されていません。「インデックス追加」をクリックしてクエリを最適化してください。',
    deleteConfirm: 'このインデックスを削除しますか？',
    selectColumns: 'インデックスのカラムを選択',
    autoGenerated: '空の場合は自動生成',
    duplicateName: 'インデックス名「{{name}}」は既に存在します',
  },

  // Unique Constraints
  unique: {
    title: 'ユニーク制約',
    addConstraint: '制約を追加',
    editConstraint: '制約を編集',
    noConstraints: 'ユニーク制約が定義されていません。「制約を追加」をクリックしてカラム間の一意性を強制してください。',
    deleteConfirm: 'この制約を削除しますか？',
    selectColumns: 'ユニーク制約のカラムを選択',
  },

  // Enum
  enum: {
    title: '列挙値',
    addValue: '値を追加',
    noValues: '列挙値が定義されていません。「値を追加」をクリックして開始してください。',
    value: '値',
    label: 'ラベル',
    extra: '追加情報',
    deleteConfirm: 'この値を削除しますか？',
    displayLabel: '表示ラベル（フォーム用）',
    extraProperties: '追加プロパティ',
    noExtraProperties: '追加プロパティはありません。bgColor、textColor、icon、orderなどのカスタムフィールドを追加できます。',
  },

  // Settings
  settings: {
    title: '設定',
    database: 'データベース',
    databaseType: 'データベースタイプ',
    databaseHint: '利用可能なインデックス型とSQL生成に影響します。',
    appearance: '外観',
    darkMode: 'ダークモード',
    showPreview: 'プレビューパネル表示',
    language: '言語',
    serverConfig: 'サーバー設定',
    schemasDir: 'スキーマディレクトリ',
    serverPort: 'サーバーポート',
    host: 'ホスト',
    plugins: 'プラグイン',
    noPlugins: 'プラグインがインストールされていません。npm install @famgia/omnify-japan でインストール',
    pluginsHint: 'プラグインを有効/無効にしてカスタム型を追加。変更後はサーバーの再起動が必要です。',
    pluginEnabled: '{{name}} プラグインを有効にしました',
    pluginDisabled: '{{name}} プラグインを無効にしました',
    pluginToggleError: 'プラグインの切り替えに失敗しました',
    serverRestarting: 'サーバー再起動中...',
    pleaseWait: 'サーバーの再起動をお待ちください',
    serverRestartFailed: 'サーバーの再起動に失敗しました。手動で再起動してください。',
    pluginConfiguration: '設定',
    savePluginConfig: '設定を保存',
    pluginConfigSaveError: 'プラグイン設定の保存に失敗しました',
  },

  // Preview
  preview: {
    title: 'コードプレビュー',
    laravel: 'Laravel',
    typescript: 'TypeScript',
    sql: 'SQL',
    laravelMigration: 'Laravelマイグレーション',
    rawSql: 'SQL生成',
    noPreview: 'プレビューがありません',
  },

  // History
  history: {
    title: 'バージョン履歴',
    version: 'バージョン',
    migration: 'マイグレーション',
    description: '説明',
    changes: '変更',
    timestamp: 'タイムスタンプ',
    noVersions: 'バージョンが見つかりません。最初のバージョンを作成するにはマイグレーションを生成してください。',
    versionDetail: 'バージョン詳細',
    driver: 'ドライバー',
    schemaSnapshot: 'スキーマスナップショット',
    noChangesRecorded: '変更が記録されていません',
    diff: '差分',
    noChangesBetween: 'バージョン間に変更はありません',
    changesDetected: '{{count}} 件の変更が検出されました',
  },

  // Changes
  changes: {
    analyzing: 'スキーマの変更を分析中...',
    errorLoading: '変更の読み込みエラー',
    unableToLoad: '変更を読み込めません',
    noChanges: '変更なし',
    upToDate: 'スキーマはバージョン{{version}}で最新です。',
    initial: '初期',
    totalChanges: '総変更数',
    added: '追加',
    modified: '変更',
    removed: '削除',
    comparingWith: 'バージョン{{version}}と比較中',
    initialVersion: '初期バージョン - すべてのスキーマが新規',
    schemasInProject: '現在のプロジェクトに{{count}}個のスキーマ',
    pendingPreview: '保留中の変更プレビュー',
    close: '閉じる',
    generateMigration: 'マイグレーション生成',
    discardChanges: '変更を破棄',
    discardConfirm: 'すべての変更を破棄しますか？',
    discardConfirmDesc: 'すべてのスキーマが最新バージョンに復元されます。この操作は取り消せません。',
    discardYes: '破棄',
    cancel: 'キャンセル',
    discardSuccess: '{{restored}}個のスキーマを復元、{{deleted}}個の新規スキーマを削除しました',
  },

  // Common errors
  error: {
    title: 'エラー',
  },

  // Validation
  validation: {
    required: '{{field}}は必須です',
    invalidName: '無効なプロパティ名です',
    selectAtLeastOne: '少なくとも1つのカラムを選択してください',
  },

  // Unsaved changes
  unsaved: {
    title: '未保存の変更',
    message: '未保存の変更があります。このページを離れますか？',
    leave: '離れる',
    stay: '留まる',
  },
};
