/**
 * Vietnamese translations
 */

export default {
  // Common
  common: {
    save: 'Lưu',
    cancel: 'Hủy',
    delete: 'Xóa',
    edit: 'Sửa',
    add: 'Thêm',
    apply: 'Áp dụng',
    update: 'Cập nhật',
    back: 'Quay lại',
    yes: 'Có',
    no: 'Không',
    loading: 'Đang tải...',
    actions: 'Thao tác',
    options: 'Tùy chọn',
    name: 'Tên',
    type: 'Kiểu',
    auto: '(tự động)',
  },

  // Header
  header: {
    pendingChanges: 'Thay đổi đang chờ',
    noChanges: 'Không có thay đổi',
    validationErrors: 'Lỗi xác thực',
    publishVersion: 'Xuất bản phiên bản',
    connected: 'Đã kết nối',
    disconnected: 'Mất kết nối',
  },

  // Navigation
  nav: {
    home: 'Trang chủ',
    settings: 'Cài đặt',
    objects: 'Đối tượng',
    enums: 'Enum',
    history: 'Lịch sử',
    newEnum: 'Enum mới',
  },

  // Home page
  home: {
    title: 'Schema',
    newSchema: 'Schema mới',
    createFirst: 'Tạo Schema đầu tiên',
    noSchemas: 'Không tìm thấy schema',
    properties: '{{count}} thuộc tính',
    values: '{{count}} giá trị',
    deleteConfirm: 'Xóa schema "{{name}}"?',
    pendingChanges: '{{count}} thay đổi',
    noChanges: 'Không có thay đổi',
    fields: 'Trường',
  },

  // Schema editor
  schema: {
    newSchema: 'Schema mới',
    editSchema: 'Sửa Schema',
    createSchema: 'Tạo Schema',
    saveChanges: 'Lưu thay đổi',
    schemaName: 'Tên Schema',
    displayName: 'Tên hiển thị',
    kind: 'Loại',
    kindObject: 'Đối tượng',
    kindEnum: 'Enum',
    singular: 'Tên số ít',
    plural: 'Tên số nhiều',
    group: 'Nhóm',
    tableName: 'Tên bảng tùy chỉnh',
    titleField: 'Trường tiêu đề',
    primaryKey: 'Auto ID',
    noPrimaryKey: 'Không',
    timestamps: 'Thời gian',
    softDelete: 'Xóa mềm',
    translations: 'Đa ngôn ngữ',
    authenticatable: 'Xác thực',
    loginIdField: 'Trường Login ID',
    passwordField: 'Trường mật khẩu',
    guardName: 'Tên Guard',
    authConfig: 'Cấu hình xác thực',
    schemaCreated: 'Đã tạo schema "{{name}}"',
    schemaSaved: 'Đã lưu schema "{{name}}"',
    // Dual-mode editor
    visualMode: 'Giao diện',
    codeMode: 'YAML',
    yamlEditor: 'Trình soạn YAML',
    yamlParseError: 'Lỗi cú pháp YAML',
    // Virtual fields
    fieldId: 'ID',
    fieldCreatedAt: 'Ngày tạo',
    fieldUpdatedAt: 'Ngày cập nhật',
    fieldDeletedAt: 'Ngày xóa',
    // Type display
    typeAssociation: 'Quan hệ',
  },

  // Properties
  property: {
    title: 'Thuộc tính',
    addProperty: 'Thêm thuộc tính',
    editProperty: 'Sửa thuộc tính',
    propertyName: 'Tên thuộc tính',
    noProperties: 'Chưa có thuộc tính. Nhấn "Thêm thuộc tính" để bắt đầu.',
    deleteConfirm: 'Xóa thuộc tính này?',
    nullable: 'Có thể null',
    unique: 'Duy nhất',
    primaryKey: 'Khóa chính',
    autoIncrement: 'Tự tăng',
    unsigned: 'Không dấu',
    positiveOnly: 'Không dấu (chỉ số dương)',
    defaultValue: 'Giá trị mặc định',
    defaultPlaceholder: 'Để trống nếu không có giá trị mặc định',
    description: 'Mô tả',
    descriptionPlaceholder: 'Mô tả/ghi chú cho trường',
    maxLength: 'Độ dài tối đa',
    precision: 'Độ chính xác (tổng số chữ số)',
    scale: 'Thang đo (số chữ số thập phân)',
    enumReference: 'Tham chiếu Enum hoặc giá trị',
    inlineEnumValues: 'Giá trị Enum nội tuyến',
    inlineEnumHint: 'Nhập giá trị và nhấn Enter. VD: active, pending, closed',
    enumSchemaRef: 'Tham chiếu Schema Enum',
    selectEnumSchema: 'Chọn schema enum',
    selectOptions: 'Tùy chọn (cho Select)',
    sourceSchema: 'Schema nguồn (cho Lookup)',
    references: 'Tham chiếu',
    settings: 'Cài đặt',
    index: 'Chỉ mục',
  },

  // Associations
  association: {
    relationType: 'Kiểu quan hệ',
    targetSchema: 'Schema đích',
    targetSchemas: 'Các Schema đích (Polymorphic)',
    morphName: 'Tên Morph',
    advancedOptions: 'Tùy chọn nâng cao',
    inversedBy: 'Inversed By',
    mappedBy: 'Mapped By',
    onDelete: 'Khi xóa',
    onUpdate: 'Khi cập nhật',
    joinTable: 'Tên bảng trung gian tùy chỉnh',
    owning: 'Phía sở hữu (có khóa ngoại)',
    standardRelations: 'Quan hệ tiêu chuẩn',
    polymorphicRelations: 'Quan hệ Polymorphic',
  },

  // Indexes
  index: {
    title: 'Chỉ mục',
    addIndex: 'Thêm chỉ mục',
    editIndex: 'Sửa chỉ mục',
    columns: 'Cột',
    indexName: 'Tên chỉ mục (tùy chọn)',
    indexType: 'Kiểu chỉ mục',
    uniqueIndex: 'Chỉ mục duy nhất',
    noIndexes: 'Chưa có chỉ mục. Nhấn "Thêm chỉ mục" để tối ưu truy vấn.',
    deleteConfirm: 'Xóa chỉ mục này?',
    selectColumns: 'Chọn cột cho chỉ mục',
    autoGenerated: 'Tự động tạo nếu để trống',
    duplicateName: 'Tên chỉ mục "{{name}}" đã tồn tại',
  },

  // Unique Constraints
  unique: {
    title: 'Ràng buộc Unique',
    addConstraint: 'Thêm ràng buộc',
    editConstraint: 'Sửa ràng buộc',
    noConstraints: 'Chưa có ràng buộc unique. Nhấn "Thêm ràng buộc" để đảm bảo tính duy nhất giữa các cột.',
    deleteConfirm: 'Xóa ràng buộc này?',
    selectColumns: 'Chọn cột cho ràng buộc unique',
  },

  // Enum
  enum: {
    title: 'Giá trị Enum',
    addValue: 'Thêm giá trị',
    noValues: 'Chưa có giá trị enum. Nhấn "Thêm giá trị" để bắt đầu.',
    value: 'Giá trị',
    label: 'Nhãn',
    extra: 'Thêm',
    deleteConfirm: 'Xóa giá trị này?',
    displayLabel: 'Nhãn hiển thị (cho form)',
    extraProperties: 'Thuộc tính bổ sung',
    noExtraProperties: 'Chưa có thuộc tính bổ sung. Thêm các trường tùy chỉnh như bgColor, textColor, icon, order, v.v.',
  },

  // Settings
  settings: {
    title: 'Cài đặt',
    database: 'Cơ sở dữ liệu',
    databaseType: 'Loại cơ sở dữ liệu',
    databaseHint: 'Ảnh hưởng đến các kiểu chỉ mục và tạo SQL.',
    appearance: 'Giao diện',
    darkMode: 'Chế độ tối',
    showPreview: 'Hiển thị bảng xem trước',
    language: 'Ngôn ngữ',
    serverConfig: 'Cấu hình máy chủ',
    schemasDir: 'Thư mục Schema',
    serverPort: 'Cổng máy chủ',
    host: 'Host',
    plugins: 'Plugins',
    noPlugins: 'Chưa cài đặt plugin nào. Cài đặt với: npm install @famgia/omnify-japan',
    pluginsHint: 'Bật/tắt plugin để thêm kiểu tùy chỉnh. Thay đổi cần khởi động lại server.',
    pluginEnabled: 'Đã bật plugin {{name}}',
    pluginDisabled: 'Đã tắt plugin {{name}}',
    pluginToggleError: 'Không thể bật/tắt plugin',
    serverRestarting: 'Đang khởi động lại Server...',
    pleaseWait: 'Vui lòng chờ server khởi động lại',
    serverRestartFailed: 'Khởi động lại server thất bại. Vui lòng khởi động lại thủ công.',
    pluginConfiguration: 'Cấu hình',
    savePluginConfig: 'Lưu cấu hình',
    pluginConfigSaveError: 'Không thể lưu cấu hình plugin',
  },

  // Preview
  preview: {
    title: 'Xem trước code',
    laravel: 'Laravel',
    typescript: 'TypeScript',
    sql: 'SQL',
    laravelMigration: 'Laravel Migration',
    rawSql: 'SQL thuần',
    noPreview: 'Không có bản xem trước',
  },

  // History
  history: {
    title: 'Lịch sử phiên bản',
    version: 'Phiên bản',
    migration: 'Migration',
    description: 'Mô tả',
    changes: 'Thay đổi',
    timestamp: 'Thời gian',
    noVersions: 'Không tìm thấy phiên bản. Tạo migration để tạo phiên bản đầu tiên.',
    versionDetail: 'Chi tiết phiên bản',
    driver: 'Driver',
    schemaSnapshot: 'Snapshot Schema',
    noChangesRecorded: 'Không có thay đổi được ghi nhận',
    diff: 'So sánh',
    noChangesBetween: 'Không có thay đổi giữa các phiên bản',
    changesDetected: '{{count}} thay đổi được phát hiện',
  },

  // Changes
  changes: {
    analyzing: 'Đang phân tích thay đổi schema...',
    errorLoading: 'Lỗi tải thay đổi',
    unableToLoad: 'Không thể tải thay đổi',
    noChanges: 'Không có thay đổi',
    upToDate: 'Schema của bạn đã cập nhật với phiên bản {{version}}.',
    initial: 'khởi tạo',
    totalChanges: 'Tổng thay đổi',
    added: 'Thêm mới',
    modified: 'Sửa đổi',
    removed: 'Đã xóa',
    comparingWith: 'So sánh với phiên bản {{version}}',
    initialVersion: 'Phiên bản đầu tiên - tất cả schema đều mới',
    schemasInProject: '{{count}} schema trong dự án hiện tại',
    pendingPreview: 'Xem trước thay đổi đang chờ',
    close: 'Đóng',
    generateMigration: 'Tạo Migration',
    discardChanges: 'Hủy thay đổi',
    discardConfirm: 'Hủy tất cả thay đổi?',
    discardConfirmDesc: 'Thao tác này sẽ khôi phục tất cả schema về phiên bản mới nhất. Không thể hoàn tác.',
    discardYes: 'Hủy',
    cancel: 'Bỏ qua',
    discardSuccess: 'Đã khôi phục {{restored}} schema, xóa {{deleted}} schema mới',
  },

  // Common errors
  error: {
    title: 'Lỗi',
  },

  // Validation
  validation: {
    required: '{{field}} là bắt buộc',
    invalidName: 'Tên thuộc tính không hợp lệ',
    selectAtLeastOne: 'Chọn ít nhất một cột',
  },

  // Unsaved changes
  unsaved: {
    title: 'Thay đổi chưa lưu',
    message: 'Bạn có thay đổi chưa lưu. Bạn có chắc muốn rời khỏi trang này?',
    leave: 'Rời đi',
    stay: 'Ở lại',
  },
};
