/**
 * Index Edit Modal component
 */

import { Modal, Form, Input, Select, Checkbox, theme } from 'antd';
import type { FormInstance } from 'antd';
import { useTranslation } from 'react-i18next';

interface IndexModalProps {
  open: boolean;
  form: FormInstance;
  editingIndex: number | null;
  propertyNames: string[];
  indexTypes: string[];
  databaseType: string;
  onOk: () => Promise<void>;
  onCancel: () => void;
}

export function IndexModal({
  open,
  form,
  editingIndex,
  propertyNames,
  indexTypes,
  databaseType,
  onOk,
  onCancel,
}: IndexModalProps): React.ReactElement {
  const { t } = useTranslation();
  const { token } = theme.useToken();

  return (
    <Modal
      title={editingIndex !== null ? t('index.editIndex') : t('index.addIndex')}
      open={open}
      onOk={onOk}
      onCancel={onCancel}
      okText={editingIndex !== null ? t('common.update') : t('common.add')}
      width={500}
    >
      <Form form={form} layout="horizontal" labelCol={{ span: 6 }} wrapperCol={{ span: 18 }} style={{ marginTop: token.margin }}>
        <Form.Item
          name="columns"
          label={t('index.columns')}
          rules={[{ required: true, message: t('validation.selectAtLeastOne') }]}
        >
          <Select
            mode="multiple"
            options={propertyNames.map((n) => ({ value: n, label: n }))}
            placeholder={t('index.selectColumns')}
          />
        </Form.Item>

        <Form.Item name="name" label={t('index.indexName')}>
          <Input placeholder={t('index.autoGenerated')} />
        </Form.Item>

        {indexTypes.length > 0 && (
          <Form.Item name="type" label={`${t('index.indexType')} (${databaseType})`}>
            <Select
              allowClear
              options={indexTypes.map((it) => ({ value: it, label: it.toUpperCase() }))}
              placeholder="Default: btree"
            />
          </Form.Item>
        )}

        <Form.Item name="unique" valuePropName="checked" noStyle>
          <Checkbox>{t('index.uniqueIndex')}</Checkbox>
        </Form.Item>
      </Form>
    </Modal>
  );
}
